### ISSUE TITLE
how can I use particials

### ISSUE THREAD

**Issue by edilsonvilarinho** [ratracegrad/nodejs_ejs_boilerplate#1]
how can I use particials with this structure https://github.com/edilsonvilarinho/express-structure

**Comment by ratracegrad** [comment]
Hello,

You would put your partials in the views/ directory probably in a folder in
the views directory called partials.  So it would look like:

views/
      partials/
              header.ejs
              footer.ejs
      index.ejs

In your index.ejs file you would include the partials from the partials
directory


Jennifer Bland

sent from my rotary phone

**Comment by edilsonvilarinho** [comment]
I got this way "app.use(express.static(process.cwd() + '/app/public'));"

var express = require('express');
var consign = require('consign');
var bodyParser = require('body-parser');
var expressValidator = require('express-validator');
var expressSession = require('express-session');

var app = express();

```
app.set( 'view engine' , 'ejs' );
app.set( 'views' , './app/views');
app.set('port', process.env.PORT_SERVER || 3001);

app.use(express.static(process.cwd() + '/app/public'));
app.use(bodyParser.urlencoded({extended : true }));
app.use(expressValidator());
app.use(expressSession({secret:'4JlXXPfp'}));
```

Thanks for listening.
